elasticsearch:
  host: 192.168.134.2
  port: 9200

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.134.2:3306/db_es
    username: root
    password: password

mybatis:
  mapper-locations: classpath:GoodsMapper.xml
  type-aliases-package: code.domain

